### ISSUE TITLE
test .travis.yml 

### ISSUE THREAD

**Issue by fabianaboldrin** [fabianaboldrin/web-crawler#12]
i'm in progress with my .travis.yml, need help testing it and ideas for improvement in it.
for more information please check #11 

![screen shot 2017-10-07 at 14 28 03](https://user-images.githubusercontent.com/29741664/31310299-ef14bfc8-ab6b-11e7-8f43-abbe427d4faa.png)

**Comment by circa10a** [comment]
can you post a link to the build output?

**Comment by fabianaboldrin** [comment]
just update the .travis.yml file with a 
`script: echo foo`
now, that the ci is passing, i wanted help with testing the code

**Comment by circa10a** [comment]
```
language: python

branches:
  only:
    - master
    - progress
    
script: 
  - echo Hello
  - pip install -r requirements.txt
  - echo Bye
  
notifications:
  email:
    recipients:
      - bibacb.fb@gmail.com
      
    on_success: [always]
    on_failure: [always]
```
